# Site settings
title: UC Davis Olive Center
email: djflynn@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  The world-renowned center brings together nearly 60 UC faculty members, research specialists and farm advisors who address the research and education needs of California olive growers and processors. The center also collaborates with institutions worldwide. The centerâ€™s co-chairs are Professor Michael McCarthy, Chair of the Department of Food Science and Technology; and Dr. Louise Ferguson, Extension Specialist in the Department of Plant Sciences.
subject: Olive research at UC Davis
classification: Web Design
themecolor: 848B14
repo: "https://github.com/ucdavis/olivecenter"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ucdavis.github.io/olivecenter" # the base hostname & protocol for your site

break: md

future: true

permalink: pretty

paginate: 3

# Build settings
markdown: kramdown

#gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - octopress-autoprefixer
# collections:
#   contents:
#     output: true
